#!/bin/bash

set -e
set -x

test -d $TARGET_DIR || mkdir -p $TARGET_DIR

pushd $UBOOT_DIR
make distclean O=$UBOOT_DIR/output
make $UBOOT_DEFCONFIG O=$UBOOT_DIR/output
make -j$JOBS O=$UBOOT_DIR/output

pushd output
cp `find . -name "env_common.o"` copy_env_common.o
arm-linux-gnueabihf-objcopy -O binary --only-section=.rodata `find . -name "copy_env_common.o"`
tr '\0' '\n' < copy_env_common.o | grep '=' > default_envs.txt
tools/mkenvimage -s 16384 -o params.bin default_envs.txt
sed -i -e 's/bootcmd=run mmcboot/bootcmd=run ramfsboot/g' default_envs.txt
tools/mkenvimage -s 16384 -o params_initrd.bin default_envs.txt
rm copy_env_common.o default_envs.txt

cp u-boot.bin $TARGET_DIR
cp spl/$UBOOT_SPL $TARGET_DIR/bl2.bin
cp params.bin params_initrd.bin $TARGET_DIR
cp u-boot $TARGET_DIR

UBOOT_VERSION=`cat include/generated/version_autogenerated.h | grep U_BOOT_VERSION | awk -F \" '{print $2}'`

echo "RELEASE_UBOOT=${UBOOT_VERSION}" >> $TARGET_DIR/artik_release

popd
rm -rf output

popd
