#!/bin/sh
#
# Start the sdcard recovery....
#

case "$1" in
start)
recovery_on=`cat /proc/cmdline | grep recovery`
if [ "$recovery_on" != "" ]; then
	echo "Starting recovery..."
	/sbin/sd_recovery.sh
fi
;;
stop)
;;
restart|reload)
"$0" stop
"$0" start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac

exit $?
